fix: update rust-overlay to a more recent version in flake.lock (#745)
This PR updates the rust-overlay via `nix flake update`, the previous
version was stuck with the Rust 1.76 toolchain and so the project
couldn't be built:

```sh
direnv: loading ~/Projects/almalinux/bluebuild/cli/.envrc
direnv: using flake
error: Cannot build '/nix/store/adyc3z90r4pq5m5z2vbjmskjpm10m2df-cargo-1.76.0-x86_64-unknown-linux-gnu.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/px40rqjp6p3yr8a7k146w7ib1jpkp14z-cargo-1.76.0-x86_64-unknown-linux-gnu
       Last 3 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/lkbacjsqhp3imp9ldyjh1qa6vrf7mayf-unknown
       > do not know how to unpack source archive /nix/store/lkbacjsqhp3imp9ldyjh1qa6vrf7mayf-unknown
       For full logs, run:
         nix log /nix/store/adyc3z90r4pq5m5z2vbjmskjpm10m2df-cargo-1.76.0-x86_64-unknown-linux-gnu.drv
error: Cannot build '/nix/store/1x0k6q3gjb1amxxx38mk506vbm8yi3id-rust-default-1.76.0.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/h40m10lc33bvy9qx6l33qdh4qlva78i9-rust-default-1.76.0
error: Cannot build '/nix/store/czgd2vk2ns4j4kh4wjj70dfm4hw0p9n0-nix-shell-env.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/04d30bawwbb8rd5601px9xik4lwx47wc-nix-shell-env
```

Signed-off-by: Esteve Fernandez <esteve@apache.org>